### ISSUE TITLE
[Question] styled-jsx or styled components?

### ISSUE THREAD

**Issue by yuvikakoul** [divyenduz/ds#9]
Should we use styled components for CSS or go with styled-jsx? 

**Here are few stats on both:** https://js.libhunt.com/project/styled-jsx/vs/styled-components
**Next bundel styled-jsx:** https://github.com/zeit/next.js#built-in-css-support
**styled-jsx documentation:** https://www.npmjs.com/package/styled-jsx

**Comment by divyenduz** [comment]
@yuvikakoul : I would prefer `styled-jsx` as it is built-in and we do not need to add another dependency. 
Let's pair on this one in a couple of days.
